# Generated by DeepSeek TUI

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('url', models.URLField(max_length=1000, verbose_name='文章链接')),
                ('cover_url', models.CharField(blank=True, default='', max_length=1000, verbose_name='封面图')),
                ('summary', models.TextField(blank=True, default='', verbose_name='文章摘要')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='分类')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='来源/作者')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='标签(JSON)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否显示')),
                ('published_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-sort_order', '-published_time', '-created_time'],
            },
        ),
    ]
