# Generated by Django 4.2.30 on 2026-08-11 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='昵称')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='配置喜好')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='UserCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.SmallIntegerField(choices=[(1, '乾造'), (0, '坤造')], verbose_name='性别')),
                ('year_ganzhi', models.CharField(max_length=10, verbose_name='年柱')),
                ('month_ganzhi', models.CharField(max_length=10, verbose_name='月柱')),
                ('day_ganzhi', models.CharField(max_length=10, verbose_name='日柱')),
                ('hour_ganzhi', models.CharField(max_length=10, verbose_name='时柱')),
                ('subject_name', models.CharField(blank=True, default='', max_length=64, verbose_name='姓名')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('input_snapshot', models.JSONField(blank=True, default=dict, verbose_name='排盘输入快照')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='保存时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_cases', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '我的案例',
                'verbose_name_plural': '我的案例',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='对象类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='uniq_user_favorite'),
        ),
    ]
