# Generated by Django 4.2.30 on 2026-09-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信 openid'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unionid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信 unionid'),
        ),
    ]
