# Generated by Django 6.0 on 2025-12-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, verbose_name='命例来源')),
                ('gender', models.SmallIntegerField(choices=[(1, '乾造'), (0, '坤造')], verbose_name='性别')),
                ('year_ganzhi', models.CharField(max_length=10, verbose_name='年柱')),
                ('month_ganzhi', models.CharField(max_length=10, verbose_name='月柱')),
                ('day_ganzhi', models.CharField(max_length=10, verbose_name='日柱')),
                ('hour_ganzhi', models.CharField(max_length=10, verbose_name='时柱')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='命例反馈')),
                ('original_url', models.URLField(blank=True, null=True, verbose_name='命例原网页地址')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='命例标签')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '命例',
                'verbose_name_plural': '命例',
            },
        ),
    ]
