# Generated by Django 4.2.30 on 2026-08-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minghub', '0003_system_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinycase',
            options={'ordering': ['id'], 'verbose_name': '命例', 'verbose_name_plural': '命例'},
        ),
    ]
